/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.multi.module.project.app;

import gradle.multi.module.project.list.LinkedList;

import static gradle.multi.module.project.utilities.StringUtils.join;
import static gradle.multi.module.project.utilities.StringUtils.split;
import static gradle.multi.module.project.app.MessageUtils.getMessage;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
